#!/usr/bin/env bash

TODO_VERSION="0.1.0"

# --- Colors --- {{{

if [ -t 1 ] && [ -z "${NO_COLOR+x}" ]; then
  RESET="\e[0m"
  BLACK="\e[30m"
  RED="\e[31m"
  GREEN="\e[32m"
  YELLOW="\e[33m"
  BLUE="\e[34m"
  MAGENTA="\e[35m"
  CYAN="\e[36m"
  WHITE="\e[37m"
else
  RESET=""
  BLACK=""
  RED=""
  GREEN=""
  YELLOW=""
  BLUE=""
  MAGENTA=""
  CYAN=""
  WHITE=""
fi

# }}}
# --- Help Message --- {{{

function print_version() {
  printf "%s, version %s\n" "$0" "$TODO_VERSION"
}

function print_help() {
  printf "%bUsage:%b %s [OPTIONS] COMMAND [ARGS]...\n" "$YELLOW" "$RESET" "$0"
  printf "\n  %s\n" "A personal todo list manager, for tracking and organizing tasks."
  printf "\n%bOptions:%b\n" "$YELLOW" "$RESET"
  printf "  %b%-10s%b  %s\n" "$GREEN" "--version" "$RESET" "Show the version and exit."
  printf "  %b%-10s%b  %s\n" "$GREEN" "-h, --help" "$RESET" "Show this message and exit."
  printf "\n%bCommands:%b\n" "$YELLOW" "$RESET"
  printf "  %b%-4s%b  %s\n" "$GREEN" "add" "$RESET" "Add a new task to the task list."
  printf "  %b%-4s%b  %s\n" "$GREEN" "done" "$RESET" "Mark an open task as completed."
}

# }}}
# --- Parse Arguments --- {{{

function parse_args() {
  while test $# -gt 0; do
    _key="$1"
    case "$_key" in
    -h | --help)
      print_help
      exit 0
      ;;
    -h*)
      print_help
      exit 0
      ;;
    --version)
      print_version
      exit 0
      ;;
    esac
  done
}

# }}}

parse_args "$@"
